volumes:
  n8n_demo_storage:
  qdrant_demo_storage:

networks:
  aidemo:

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: ['aidemo']
  environment:
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
    - OLLAMA_HOST=host.docker.internal:11434
    # - OLLAMA_HOST=ollama:11434

services:
  n8n-auto:
    <<: *service-n8n
    hostname: n8n-auto
    container_name: n8n-auto
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - n8n_demo_storage:/home/node/.n8n

  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    container_name: qdrant
    networks: ['aidemo']
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - qdrant_demo_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__ENABLE_DASHBOARD=true